# Generated by Django 4.2.11 on 2024-04-18 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpfuldiary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordedaudio',
            name='name',
        ),
    ]
